env:
  global:
  - secure: Od2ZYUhrfms2EKvWZ+fhiy2aUMKO5v8km9gvRpLs3fQx/Wo23oQwVVx1lNE/bIZ9Uea596d/Y5VnSkZ4r7HRhwyyMw7F2M+5wbW+RIfHN05XaDma3H9ulF94mWQiMrbT9yFur3AeKb+Wwavl6U0bH7/DsFcXLq/z+1GaRNH/Bnc=

language: python
python:
  - "2.7"
  - "3.3"
  - "3.5"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev libxml2-utils
script:
  - ./scripts/test.sh

after_success:
  - ./scripts/travis_update_generated_repos.sh

